import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('zh'),
  ];

  static AppLocalizations of(BuildContext context) {
    final localizations =
        Localizations.of<AppLocalizations>(context, AppLocalizations);
    if (localizations == null) {
      throw StateError('AppLocalizations not found in context');
    }
    return localizations;
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'app_title': 'MyPassword',
      'create_vault': 'Create Vault',
      'master_password': 'Master password',
      'create_vault_action': 'Create vault',
      'unlock_vault': 'Unlock Vault',
      'unlock': 'Unlock',
      'unlocking': 'Unlocking...',
      'creating': 'Creating...',
      'passwords': 'Passwords',
      'settings': 'Settings',
      'local_backup': 'Local Backup',
      'webdav_sync': 'WebDAV Sync',
      'webdav_guide': 'WebDAV Guide',
      'webdav_guide_desc': 'How to configure Jianguoyun and other WebDAV drives',
      'sync_status': 'Sync Status',
      'sync_status_desc': 'View current sync status, remote info, and recent activity',
      'sync_conflict_title': 'Sync Conflict',
      'sync_conflict_description':
          'Both local data and the remote sync package have possible new changes. Choose which side to keep before continuing.',
      'sync_conflict_no_longer_exists':
          'No sync conflict is currently detected. You can still manually upload or restore if needed.',
      'sync_conflict_local_side': 'Local side',
      'sync_conflict_remote_side': 'Remote side',
      'sync_conflict_how_to_handle': 'How to handle',
      'sync_conflict_keep_local_hint':
          'Keep current local vault and upload it to overwrite the remote sync package.',
      'sync_conflict_keep_local_action': 'Keep local and upload',
      'sync_conflict_keep_remote_hint':
          'Keep the remote sync package and restore it into the current vault.',
      'sync_conflict_keep_remote_action': 'Keep remote and restore',
      'sync_conflict_handle_later': 'Handle later',
      'sync_overview': 'Sync Overview',
      'sync_type': 'Sync type',
      'sync_configuration_status': 'Configuration status',
      'sync_configured': 'Configured',
      'sync_not_configured': 'Not configured',
      'sync_enabled': 'Enabled',
      'sync_disabled': 'Disabled',
      'sync_recent_activity': 'Recent activity',
      'sync_last_local_change': 'Last local change',
      'sync_last_upload': 'Last upload',
      'sync_last_restore': 'Last restore',
      'sync_last_error': 'Last error',
      'sync_no_errors': 'No errors',
      'sync_remote_status': 'Remote status',
      'sync_remote_package': 'Remote package',
      'sync_remote_package_exists': 'Exists',
      'sync_remote_updated_at': 'Remote updated at',
      'sync_remote_file_size': 'Remote file size',
      'sync_actions': 'Actions',
      'webdav_sync_config': 'WebDAV Configuration',
      'webdav_sync_desc': 'Configure your own WebDAV cloud drive for encrypted sync packages.',
      'webdav_sync_desc_short': 'Configure Jianguoyun or another WebDAV drive',
      'webdav_base_url': 'WebDAV base URL',
      'webdav_username': 'WebDAV username',
      'webdav_password': 'WebDAV app password',
      'webdav_remote_path': 'Remote sync path',
      'webdav_base_url_required': 'WebDAV base URL is required',
      'webdav_username_required': 'WebDAV username is required',
      'webdav_password_required': 'WebDAV app password is required',
      'webdav_remote_path_required': 'Remote sync path is required',
      'webdav_saved': 'WebDAV settings saved',
      'webdav_save_failed': 'Unable to save WebDAV settings',
      'webdav_upload_now': 'Upload To WebDAV',
      'webdav_restore_now': 'Restore From WebDAV',
      'webdav_not_configured': 'WebDAV sync is not configured',
      'webdav_upload_success': 'Uploaded sync package to WebDAV',
      'webdav_restore_success': 'Restored sync package from WebDAV',
      'webdav_action_failed': 'WebDAV action failed',
      'webdav_test_connection': 'Test WebDAV Connection',
      'webdav_connection_success': 'WebDAV connection succeeded',
      'webdav_auth_failed': 'WebDAV authentication failed',
      'webdav_remote_file_missing': 'Remote sync package was not found',
      'webdav_network_error': 'Unable to connect to the WebDAV server',
      'webdav_invalid_config': 'WebDAV settings are invalid',
      'webdav_guide_what_you_need': 'What you need before configuration',
      'webdav_guide_need_account': 'A WebDAV-enabled cloud drive account, such as Jianguoyun.',
      'webdav_guide_need_app_password': 'An app password generated by the cloud drive, not your login SMS code.',
      'webdav_guide_need_address': 'The correct WebDAV server address provided by the cloud drive.',
      'webdav_guide_jianguoyun_example': 'Jianguoyun example',
      'webdav_guide_username_hint': 'Your Jianguoyun login account, usually email or phone number',
      'webdav_guide_password_hint': 'Paste the app password generated in Jianguoyun security settings',
      'webdav_guide_how_to_get_password': 'How to get the Jianguoyun app password',
      'webdav_guide_step_open_jianguoyun': 'Open Jianguoyun, then go to account settings.',
      'webdav_guide_step_security': 'Find security settings or third-party app management.',
      'webdav_guide_step_app_password': 'Create a new app password for WebDAV.',
      'webdav_guide_step_paste_password': 'Copy that app password back into this app to test and save.',
      'webdav_guide_usage_flow': 'Recommended usage flow',
      'webdav_guide_flow_config': 'Open WebDAV configuration and fill in address, username, app password, and remote path.',
      'webdav_guide_flow_test': 'Tap Test WebDAV Connection first. If successful, the config will be saved automatically.',
      'webdav_guide_flow_upload': 'Use Upload To WebDAV to manually send the latest encrypted sync package.',
      'webdav_guide_flow_restore': 'Use Restore From WebDAV on another device, then enter the backup package password to import.',
      'webdav_guide_tip': 'If the test succeeds but upload fails, usually check whether the current master password is correct or whether the remote path was modified incorrectly.',
      'invalid_current_master_password': 'Current master password is incorrect',
      'auto_sync_on_change': 'Auto sync after local changes',
      'auto_sync_on_change_desc':
          'Automatically upload the encrypted sync package after save, delete, import, or password change.',
      'remote_sync_update_available':
          'A newer sync package was found in WebDAV. Restore it from Settings if needed.',
      'remote_sync_conflict':
          'Both local data and WebDAV may have new changes. Review manually before restoring.',
      'dismiss': 'Dismiss',
      'enter_master_password': 'Enter master password',
      'confirm_action': 'Confirm',
      'no_credentials_yet': 'No credentials yet',
      'search_hint': 'Search by title or domain',
      'new_credential': 'New Credential',
      'edit_credential': 'Edit Credential',
      'title': 'Title',
      'username': 'Username',
      'password': 'Password',
      'website': 'Website',
      'notes': 'Notes',
      'favorite': 'Favorite',
      'save': 'Save',
      'saving': 'Saving...',
      'generate_password': 'Generate password',
      'credential': 'Credential',
      'credential_not_found': 'Credential not found',
      'unable_to_load_credential': 'Unable to load credential',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'delete_credential_title': 'Delete credential',
      'delete_credential_message':
          'Are you sure you want to delete this credential?',
      'updated': 'Updated',
      'lock_vault_now': 'Lock vault now',
      'disable_biometric_unlock': 'Disable biometric unlock',
      'biometric_unlock_disabled': 'Biometric unlock disabled',
      'change_master_password': 'Change master password',
      'current_master_password': 'Current master password',
      'new_master_password': 'New master password',
      'confirm_new_master_password': 'Confirm new master password',
      'master_password_updated': 'Master password updated',
      'master_password_mismatch': 'Passwords do not match',
      'unable_to_change_master_password': 'Unable to change master password',
      'choose_export_directory': 'Choose export directory',
      'export_directory': 'Export directory',
      'export_directory_required': 'Please choose an export directory',
      'export_directory_not_set': 'Not set',
      'export_cancelled': 'Export cancelled',
      'backup_master_password': 'Backup file master password',
      'invalid_backup_master_password': 'Backup file master password is incorrect',
      'selected_backup_file': 'Selected backup file',
      'choose_backup_file_first': 'Choose backup file first',
      'start_import': 'Start import',
      'vault_lock_timing': 'Vault lock timing',
      'lock_when_app_backgrounded': 'Lock when app goes to background',
      'lock_when_app_exit': 'Lock only after app process ends',
      'export_backup': 'Export backup',
      'import_backup': 'Import backup',
      'export_backup_desc':
          'Exports an encrypted backup file into the app documents directory.',
      'export_backup_action': 'Export backup',
      'exporting': 'Exporting...',
      'backup_created_at': 'Backup file created at:',
      'backup_encrypted_notice':
          'This file is encrypted and can be imported only while the vault is unlocked.',
      'import_backup_desc':
          'Select an encrypted backup file exported by this app.',
      'choose_backup_file': 'Choose backup file',
      'importing': 'Importing...',
      'import_cancelled': 'Import cancelled',
      'unable_to_export_backup': 'Unable to export backup',
      'unable_to_import_backup': 'Unable to import backup',
      'password_generator': 'Password Generator',
      'length': 'Length',
      'uppercase': 'Uppercase',
      'lowercase': 'Lowercase',
      'numbers': 'Numbers',
      'symbols': 'Symbols',
      'regenerate': 'Regenerate',
      'use_this_password': 'Use this password',
      'select_at_least_one_option': 'Select at least one option',
      'language': 'Language',
      'language_system': 'Use system language',
      'language_english': 'English',
      'language_chinese': '中文',
      'biometrics_unavailable': 'Biometrics unavailable',
      'biometric_authentication_failed': 'Biometric authentication failed',
      'biometric_unlock_unavailable': 'Biometric unlock unavailable',
      'enable_biometric_unlock': 'Enable biometric unlock',
      'biometric_unlock_enabled': 'Biometric unlock enabled',
      'biometric_unlock_enable_failed': 'Unable to enable biometric unlock',
      'biometric_unlock_not_enabled': 'Biometric unlock is not enabled',
      'unable_to_unlock_vault': 'Unable to unlock vault',
      'unable_to_create_vault': 'Unable to create vault',
      'master_password_required': 'Master password is required',
      'title_required': 'Title is required',
      'password_required': 'Password is required',
      'imported_count': 'Imported {count} credentials',
      'use_biometrics': 'Use biometrics',
      'no_domain': 'No domain',
      'category': 'Category',
      'copy_username': 'Copy username',
      'copy_password': 'Copy password',
      'copied_username': 'Username copied',
      'copied_password': 'Password copied',
      'no_username': 'No username',
    },
    'zh': {
      'app_title': 'MyPassword',
      'create_vault': '创建保险库',
      'master_password': '主密码',
      'create_vault_action': '创建保险库',
      'unlock_vault': '解锁保险库',
      'unlock': '解锁',
      'unlocking': '解锁中...',
      'creating': '创建中...',
      'passwords': '密码',
      'settings': '设置',
      'local_backup': '本地备份',
      'webdav_sync': 'WebDAV 同步',
      'webdav_guide': 'WebDAV 使用说明',
      'webdav_guide_desc': '查看坚果云等 WebDAV 网盘的配置方法',
      'sync_status': '同步状态',
      'sync_status_desc': '查看当前同步状态、远端信息和最近活动',
      'sync_conflict_title': '同步冲突处理',
      'sync_conflict_description': '检测到本地数据和远端同步包都可能有新变化，请先确认要保留哪一侧。',
      'sync_conflict_no_longer_exists': '当前没有检测到同步冲突，如有需要你仍然可以手动上传或恢复。',
      'sync_conflict_local_side': '本地侧信息',
      'sync_conflict_remote_side': '远端侧信息',
      'sync_conflict_how_to_handle': '处理方式',
      'sync_conflict_keep_local_hint': '保留当前本地保险库，并上传覆盖远端同步包。',
      'sync_conflict_keep_local_action': '保留本地并上传',
      'sync_conflict_keep_remote_hint': '保留远端同步包，并将其恢复导入到当前保险库。',
      'sync_conflict_keep_remote_action': '保留远端并恢复',
      'sync_conflict_handle_later': '稍后处理',
      'sync_overview': '同步概览',
      'sync_type': '同步方式',
      'sync_configuration_status': '配置状态',
      'sync_configured': '已配置',
      'sync_not_configured': '未配置',
      'sync_enabled': '已开启',
      'sync_disabled': '未开启',
      'sync_recent_activity': '最近活动',
      'sync_last_local_change': '最近本地变更',
      'sync_last_upload': '最近上传',
      'sync_last_restore': '最近恢复',
      'sync_last_error': '最近错误',
      'sync_no_errors': '无',
      'sync_remote_status': '远端状态',
      'sync_remote_package': '远端同步包',
      'sync_remote_package_exists': '已存在',
      'sync_remote_updated_at': '远端更新时间',
      'sync_remote_file_size': '远端文件大小',
      'sync_actions': '操作',
      'webdav_sync_config': 'WebDAV 配置',
      'webdav_sync_desc': '配置你自己的 WebDAV 网盘，用于同步加密同步包。',
      'webdav_sync_desc_short': '配置坚果云或其他 WebDAV 网盘',
      'webdav_base_url': 'WebDAV 地址',
      'webdav_username': 'WebDAV 用户名',
      'webdav_password': 'WebDAV 应用密码',
      'webdav_remote_path': '远端同步路径',
      'webdav_base_url_required': '请输入 WebDAV 地址',
      'webdav_username_required': '请输入 WebDAV 用户名',
      'webdav_password_required': '请输入 WebDAV 应用密码',
      'webdav_remote_path_required': '请输入远端同步路径',
      'webdav_saved': 'WebDAV 设置已保存',
      'webdav_save_failed': '无法保存 WebDAV 设置',
      'webdav_upload_now': '上传到 WebDAV',
      'webdav_restore_now': '从 WebDAV 恢复',
      'webdav_not_configured': '尚未配置 WebDAV 同步',
      'webdav_upload_success': '已上传同步包到 WebDAV',
      'webdav_restore_success': '已从 WebDAV 恢复同步包',
      'webdav_action_failed': 'WebDAV 操作失败',
      'webdav_test_connection': '测试 WebDAV 连接',
      'webdav_connection_success': 'WebDAV 连接成功',
      'webdav_auth_failed': 'WebDAV 认证失败',
      'webdav_remote_file_missing': '未找到远端同步包',
      'webdav_network_error': '无法连接到 WebDAV 服务器',
      'webdav_invalid_config': 'WebDAV 配置无效',
      'webdav_guide_what_you_need': '配置前你需要准备',
      'webdav_guide_need_account': '一个支持 WebDAV 的网盘账号，例如坚果云。',
      'webdav_guide_need_app_password': '网盘生成的应用密码，而不是短信验证码或网页登录密码。',
      'webdav_guide_need_address': '网盘官方提供的正确 WebDAV 服务器地址。',
      'webdav_guide_jianguoyun_example': '坚果云示例',
      'webdav_guide_username_hint': '你的坚果云登录账号，一般是邮箱或手机号',
      'webdav_guide_password_hint': '填写你在坚果云安全设置里生成的应用密码',
      'webdav_guide_how_to_get_password': '如何获取坚果云应用密码',
      'webdav_guide_step_open_jianguoyun': '打开坚果云，进入账号设置。',
      'webdav_guide_step_security': '找到安全设置或第三方应用管理。',
      'webdav_guide_step_app_password': '新建一个用于 WebDAV 的应用密码。',
      'webdav_guide_step_paste_password': '把生成的应用密码复制回本应用，然后测试连接并保存。',
      'webdav_guide_usage_flow': '推荐使用流程',
      'webdav_guide_flow_config': '先进入 WebDAV 配置，填写地址、用户名、应用密码和远端路径。',
      'webdav_guide_flow_test': '先点击测试 WebDAV 连接，成功后会自动保存配置。',
      'webdav_guide_flow_upload': '再使用“上传到 WebDAV”手动上传最新加密同步包。',
      'webdav_guide_flow_restore': '换设备后使用“从 WebDAV 恢复”，再输入同步包主密码导入。',
      'webdav_guide_tip': '如果测试成功但上传失败，通常优先检查当前主密码是否正确，或者远端路径是否被错误修改。',
      'invalid_current_master_password': '当前主密码错误',
      'auto_sync_on_change': '本地变更后自动同步',
      'auto_sync_on_change_desc': '在保存、删除、导入、修改主密码后自动上传加密同步包。',
      'remote_sync_update_available': 'WebDAV 上发现较新的同步包，如需恢复请前往设置。',
      'remote_sync_conflict': '本地和 WebDAV 都可能有新变化，恢复前请先手动确认。',
      'dismiss': '关闭',
      'enter_master_password': '请输入主密码',
      'confirm_action': '确认',
      'no_credentials_yet': '还没有凭据',
      'search_hint': '按标题或域名搜索',
      'new_credential': '新增凭据',
      'edit_credential': '编辑凭据',
      'title': '标题',
      'username': '用户名',
      'password': '密码',
      'website': '网站',
      'notes': '备注',
      'favorite': '收藏',
      'save': '保存',
      'saving': '保存中...',
      'generate_password': '生成密码',
      'credential': '凭据',
      'credential_not_found': '未找到凭据',
      'unable_to_load_credential': '无法加载凭据',
      'delete': '删除',
      'cancel': '取消',
      'delete_credential_title': '删除条目',
      'delete_credential_message': '确定要删除这个条目吗？',
      'updated': '更新时间',
      'lock_vault_now': '立即锁定保险库',
      'disable_biometric_unlock': '关闭生物识别解锁',
      'biometric_unlock_disabled': '已关闭生物识别解锁',
      'change_master_password': '修改主密码',
      'current_master_password': '当前主密码',
      'new_master_password': '新主密码',
      'confirm_new_master_password': '确认新主密码',
      'master_password_updated': '主密码已更新',
      'master_password_mismatch': '两次输入的密码不一致',
      'unable_to_change_master_password': '无法修改主密码',
      'choose_export_directory': '选择导出目录',
      'export_directory': '导出目录',
      'export_directory_required': '请选择导出目录',
      'export_directory_not_set': '未设置',
      'export_cancelled': '已取消导出',
      'backup_master_password': '备份文件主密码',
      'invalid_backup_master_password': '备份文件主密码错误',
      'selected_backup_file': '已选择备份文件',
      'choose_backup_file_first': '请先选择备份文件',
      'start_import': '开始导入',
      'vault_lock_timing': '保险库锁定时机',
      'lock_when_app_backgrounded': '应用切到后台时立即锁定',
      'lock_when_app_exit': '仅在应用进程结束后锁定',
      'export_backup': '导出备份',
      'import_backup': '导入备份',
      'export_backup_desc': '将加密备份文件导出到应用文档目录。',
      'export_backup_action': '导出备份',
      'exporting': '导出中...',
      'backup_created_at': '备份文件已生成于：',
      'backup_encrypted_notice': '该文件已加密，只能在保险库解锁时导入。',
      'import_backup_desc': '选择由本应用导出的加密备份文件。',
      'choose_backup_file': '选择备份文件',
      'importing': '导入中...',
      'import_cancelled': '已取消导入',
      'unable_to_export_backup': '无法导出备份',
      'unable_to_import_backup': '无法导入备份',
      'password_generator': '密码生成器',
      'length': '长度',
      'uppercase': '大写字母',
      'lowercase': '小写字母',
      'numbers': '数字',
      'symbols': '符号',
      'regenerate': '重新生成',
      'use_this_password': '使用此密码',
      'select_at_least_one_option': '请至少选择一种字符类型',
      'language': '语言',
      'language_system': '跟随系统',
      'language_english': 'English',
      'language_chinese': '中文',
      'biometrics_unavailable': '设备不支持生物识别',
      'biometric_authentication_failed': '生物识别验证失败',
      'biometric_unlock_unavailable': '当前无法使用生物识别解锁',
      'enable_biometric_unlock': '启用生物识别解锁',
      'biometric_unlock_enabled': '已启用生物识别解锁',
      'biometric_unlock_enable_failed': '无法启用生物识别解锁',
      'biometric_unlock_not_enabled': '当前未启用生物识别解锁',
      'unable_to_unlock_vault': '无法解锁保险库',
      'unable_to_create_vault': '无法创建保险库',
      'master_password_required': '请输入主密码',
      'title_required': '请输入标题',
      'password_required': '请输入密码',
      'imported_count': '已导入 {count} 条凭据',
      'use_biometrics': '使用生物识别',
      'no_domain': '无域名',
      'category': '分类',
      'copy_username': '复制用户名',
      'copy_password': '复制密码',
      'copied_username': '用户名已复制',
      'copied_password': '密码已复制',
      'no_username': '无用户名',
    },
  };

  String _value(String key) {
    final languageCode =
        _values.containsKey(locale.languageCode) ? locale.languageCode : 'en';
    return _values[languageCode]![key] ?? _values['en']![key] ?? key;
  }

  String get appTitle => _value('app_title');
  String get createVault => _value('create_vault');
  String get masterPassword => _value('master_password');
  String get createVaultAction => _value('create_vault_action');
  String get unlockVault => _value('unlock_vault');
  String get unlock => _value('unlock');
  String get unlocking => _value('unlocking');
  String get creating => _value('creating');
  String get passwords => _value('passwords');
  String get settings => _value('settings');
  String get localBackup => _value('local_backup');
  String get webDavSync => _value('webdav_sync');
  String get webDavGuide => _value('webdav_guide');
  String get webDavGuideDesc => _value('webdav_guide_desc');
  String get syncStatus => _value('sync_status');
  String get syncStatusDesc => _value('sync_status_desc');
  String get syncConflictTitle => _value('sync_conflict_title');
  String get syncConflictDescription => _value('sync_conflict_description');
  String get syncConflictNoLongerExists =>
      _value('sync_conflict_no_longer_exists');
  String get syncConflictLocalSide => _value('sync_conflict_local_side');
  String get syncConflictRemoteSide => _value('sync_conflict_remote_side');
  String get syncConflictHowToHandle =>
      _value('sync_conflict_how_to_handle');
  String get syncConflictKeepLocalHint =>
      _value('sync_conflict_keep_local_hint');
  String get syncConflictKeepLocalAction =>
      _value('sync_conflict_keep_local_action');
  String get syncConflictKeepRemoteHint =>
      _value('sync_conflict_keep_remote_hint');
  String get syncConflictKeepRemoteAction =>
      _value('sync_conflict_keep_remote_action');
  String get syncConflictHandleLater =>
      _value('sync_conflict_handle_later');
  String get syncOverview => _value('sync_overview');
  String get syncType => _value('sync_type');
  String get syncConfigurationStatus => _value('sync_configuration_status');
  String get syncConfigured => _value('sync_configured');
  String get syncNotConfigured => _value('sync_not_configured');
  String get syncEnabled => _value('sync_enabled');
  String get syncDisabled => _value('sync_disabled');
  String get syncRecentActivity => _value('sync_recent_activity');
  String get syncLastLocalChange => _value('sync_last_local_change');
  String get syncLastUpload => _value('sync_last_upload');
  String get syncLastRestore => _value('sync_last_restore');
  String get syncLastError => _value('sync_last_error');
  String get syncNoErrors => _value('sync_no_errors');
  String get syncRemoteStatus => _value('sync_remote_status');
  String get syncRemotePackage => _value('sync_remote_package');
  String get syncRemotePackageExists => _value('sync_remote_package_exists');
  String get syncRemoteUpdatedAt => _value('sync_remote_updated_at');
  String get syncRemoteFileSize => _value('sync_remote_file_size');
  String get syncActions => _value('sync_actions');
  String get webDavSyncConfig => _value('webdav_sync_config');
  String get webDavSyncDesc => _value('webdav_sync_desc');
  String get webDavSyncDescShort => _value('webdav_sync_desc_short');
  String get webDavBaseUrl => _value('webdav_base_url');
  String get webDavUsername => _value('webdav_username');
  String get webDavPassword => _value('webdav_password');
  String get webDavRemotePath => _value('webdav_remote_path');
  String get webDavBaseUrlRequired => _value('webdav_base_url_required');
  String get webDavUsernameRequired => _value('webdav_username_required');
  String get webDavPasswordRequired => _value('webdav_password_required');
  String get webDavRemotePathRequired =>
      _value('webdav_remote_path_required');
  String get webDavSaved => _value('webdav_saved');
  String get webDavSaveFailed => _value('webdav_save_failed');
  String get webDavUploadNow => _value('webdav_upload_now');
  String get webDavRestoreNow => _value('webdav_restore_now');
  String get webDavNotConfigured => _value('webdav_not_configured');
  String get webDavUploadSuccess => _value('webdav_upload_success');
  String get webDavRestoreSuccess => _value('webdav_restore_success');
  String get webDavActionFailed => _value('webdav_action_failed');
  String get webDavTestConnection => _value('webdav_test_connection');
  String get webDavConnectionSuccess => _value('webdav_connection_success');
  String get webDavAuthFailed => _value('webdav_auth_failed');
  String get webDavRemoteFileMissing => _value('webdav_remote_file_missing');
  String get webDavNetworkError => _value('webdav_network_error');
  String get webDavInvalidConfig => _value('webdav_invalid_config');
  String get webDavGuideWhatYouNeed => _value('webdav_guide_what_you_need');
  String get webDavGuideNeedAccount => _value('webdav_guide_need_account');
  String get webDavGuideNeedAppPassword =>
      _value('webdav_guide_need_app_password');
  String get webDavGuideNeedAddress => _value('webdav_guide_need_address');
  String get webDavGuideJianguoyunExample =>
      _value('webdav_guide_jianguoyun_example');
  String get webDavGuideUsernameHint => _value('webdav_guide_username_hint');
  String get webDavGuidePasswordHint => _value('webdav_guide_password_hint');
  String get webDavGuideHowToGetPassword =>
      _value('webdav_guide_how_to_get_password');
  String get webDavGuideStepOpenJianguoyun =>
      _value('webdav_guide_step_open_jianguoyun');
  String get webDavGuideStepSecurity =>
      _value('webdav_guide_step_security');
  String get webDavGuideStepAppPassword =>
      _value('webdav_guide_step_app_password');
  String get webDavGuideStepPastePassword =>
      _value('webdav_guide_step_paste_password');
  String get webDavGuideUsageFlow => _value('webdav_guide_usage_flow');
  String get webDavGuideFlowConfig => _value('webdav_guide_flow_config');
  String get webDavGuideFlowTest => _value('webdav_guide_flow_test');
  String get webDavGuideFlowUpload => _value('webdav_guide_flow_upload');
  String get webDavGuideFlowRestore => _value('webdav_guide_flow_restore');
  String get webDavGuideTip => _value('webdav_guide_tip');
  String get invalidCurrentMasterPassword =>
      _value('invalid_current_master_password');
  String get autoSyncOnChange => _value('auto_sync_on_change');
  String get autoSyncOnChangeDesc => _value('auto_sync_on_change_desc');
  String get remoteSyncUpdateAvailable =>
      _value('remote_sync_update_available');
  String get remoteSyncConflict => _value('remote_sync_conflict');
  String get dismiss => _value('dismiss');
  String get enterMasterPassword => _value('enter_master_password');
  String get confirmAction => _value('confirm_action');
  String get noCredentialsYet => _value('no_credentials_yet');
  String get searchHint => _value('search_hint');
  String get newCredential => _value('new_credential');
  String get editCredential => _value('edit_credential');
  String get title => _value('title');
  String get username => _value('username');
  String get password => _value('password');
  String get website => _value('website');
  String get notes => _value('notes');
  String get favorite => _value('favorite');
  String get save => _value('save');
  String get saving => _value('saving');
  String get generatePassword => _value('generate_password');
  String get credential => _value('credential');
  String get credentialNotFound => _value('credential_not_found');
  String get unableToLoadCredential => _value('unable_to_load_credential');
  String get delete => _value('delete');
  String get cancel => _value('cancel');
  String get deleteCredentialTitle => _value('delete_credential_title');
  String get deleteCredentialMessage => _value('delete_credential_message');
  String get updated => _value('updated');
  String get lockVaultNow => _value('lock_vault_now');
  String get disableBiometricUnlock => _value('disable_biometric_unlock');
  String get biometricUnlockDisabled => _value('biometric_unlock_disabled');
  String get changeMasterPassword => _value('change_master_password');
  String get currentMasterPassword => _value('current_master_password');
  String get newMasterPassword => _value('new_master_password');
  String get confirmNewMasterPassword =>
      _value('confirm_new_master_password');
  String get masterPasswordUpdated => _value('master_password_updated');
  String get masterPasswordMismatch => _value('master_password_mismatch');
  String get unableToChangeMasterPassword =>
      _value('unable_to_change_master_password');
  String get chooseExportDirectory => _value('choose_export_directory');
  String get exportDirectory => _value('export_directory');
  String get exportDirectoryRequired => _value('export_directory_required');
  String get exportDirectoryNotSet => _value('export_directory_not_set');
  String get exportCancelled => _value('export_cancelled');
  String get backupMasterPassword => _value('backup_master_password');
  String get invalidBackupMasterPassword =>
      _value('invalid_backup_master_password');
  String get selectedBackupFile => _value('selected_backup_file');
  String get chooseBackupFileFirst => _value('choose_backup_file_first');
  String get startImport => _value('start_import');
  String get vaultLockTiming => _value('vault_lock_timing');
  String get lockWhenAppBackgrounded => _value('lock_when_app_backgrounded');
  String get lockWhenAppExit => _value('lock_when_app_exit');
  String get exportBackup => _value('export_backup');
  String get importBackup => _value('import_backup');
  String get exportBackupDesc => _value('export_backup_desc');
  String get exportBackupAction => _value('export_backup_action');
  String get exporting => _value('exporting');
  String get backupCreatedAt => _value('backup_created_at');
  String get backupEncryptedNotice => _value('backup_encrypted_notice');
  String get importBackupDesc => _value('import_backup_desc');
  String get chooseBackupFile => _value('choose_backup_file');
  String get importing => _value('importing');
  String get importCancelled => _value('import_cancelled');
  String get unableToExportBackup => _value('unable_to_export_backup');
  String get unableToImportBackup => _value('unable_to_import_backup');
  String get passwordGenerator => _value('password_generator');
  String get length => _value('length');
  String get uppercase => _value('uppercase');
  String get lowercase => _value('lowercase');
  String get numbers => _value('numbers');
  String get symbols => _value('symbols');
  String get regenerate => _value('regenerate');
  String get useThisPassword => _value('use_this_password');
  String get selectAtLeastOneOption => _value('select_at_least_one_option');
  String get language => _value('language');
  String get languageSystem => _value('language_system');
  String get languageEnglish => _value('language_english');
  String get languageChinese => _value('language_chinese');
  String get biometricsUnavailable => _value('biometrics_unavailable');
  String get biometricAuthenticationFailed =>
      _value('biometric_authentication_failed');
  String get biometricUnlockUnavailable =>
      _value('biometric_unlock_unavailable');
  String get enableBiometricUnlock => _value('enable_biometric_unlock');
  String get biometricUnlockEnabled => _value('biometric_unlock_enabled');
  String get biometricUnlockEnableFailed =>
      _value('biometric_unlock_enable_failed');
  String get biometricUnlockNotEnabled =>
      _value('biometric_unlock_not_enabled');
  String get unableToUnlockVault => _value('unable_to_unlock_vault');
  String get unableToCreateVault => _value('unable_to_create_vault');
  String get masterPasswordRequired => _value('master_password_required');
  String get titleRequired => _value('title_required');
  String get passwordRequired => _value('password_required');
  String get useBiometrics => _value('use_biometrics');
  String get noDomain => _value('no_domain');
  String get category => _value('category');
  String get copyUsername => _value('copy_username');
  String get copyPassword => _value('copy_password');
  String get copiedUsername => _value('copied_username');
  String get copiedPassword => _value('copied_password');
  String get noUsername => _value('no_username');

  String importedCount(int count) {
    return _value('imported_count').replaceFirst('{count}', '$count');
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((item) => item.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
